name: Rails CI
on:
  push:
    branches: [ '*' ]
concurrency:
  group: "gh-actions"
  cancel-in-progress: true
permissions:
  id-token: write
  contents: read
jobs:
  test:
    uses: ./.github/workflows/workflow_rails-specs.yml
    secrets:
      SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
      SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}

  static:
    uses: ./.github/workflows/workflow_rails-static-analysis.yml

  success_notification:
    uses: ./.github/workflows/workflow_slack-notification.yml
    needs: [ test, static ]
    if: ${{ success() }}
    secrets:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    with:
      DISPLAYED_USERNAME: Trucode JS SDK Build CI
      MESSAGE: 'CI run completed successfully! :tada: :tada:'
      COLOR: good

  failure_notification:
    uses: ./.github/workflows/workflow_slack-notification.yml
    needs: [ test, static ]
    if: ${{ failure() }}
    secrets:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    with:
      DISPLAYED_USERNAME: Trucode JS SDK Build CI
      MESSAGE: 'CI run failed! Shame! Shame! :sadpanda: :sadpanda:'
      COLOR: danger
